package com.kiran.multithreading;

public class Constructors {

// Thread class constructors:

//1. Thread t=new Thread();
//2. Thread t=new Thread(Runnable r);
//3. Thread t=new Thread(String name);
//4. Thread t=new Thread(Runnable r,String name);
//5. Thread t=new Thread(ThreadGroup g,String name);
//6. Thread t=new Thread(ThreadGroup g,Runnable r);
//7. Thread t=new Thread(ThreadGroup g,Runnable r,String name);
//8. Thread t=new Thread(ThreadGroup g,Runnable r,String name,long stackSize);

// Getting and setting name of a Thread:

//  Every Thread in java has some name it may be provided explicitly by the
//programmer or automatically generated by JVM.
// Thread class defines the following methods to get and set name of a Thread.
//1. public final String getName()
//2. public final void setName(String name)

}
